// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type claude_monitorSslReadArgs struct {
	_   structs.HostLayout
	Buf uint64
	Num uint64
}

// loadClaude_monitor returns the embedded CollectionSpec for claude_monitor.
func loadClaude_monitor() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Claude_monitorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load claude_monitor: %w", err)
	}

	return spec, err
}

// loadClaude_monitorObjects loads claude_monitor and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*claude_monitorObjects
//	*claude_monitorPrograms
//	*claude_monitorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadClaude_monitorObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadClaude_monitor()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// claude_monitorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type claude_monitorSpecs struct {
	claude_monitorProgramSpecs
	claude_monitorMapSpecs
	claude_monitorVariableSpecs
}

// claude_monitorProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type claude_monitorProgramSpecs struct {
	UprobeSslReadEntry *ebpf.ProgramSpec `ebpf:"uprobe_ssl_read_entry"`
	UprobeSslReadExit  *ebpf.ProgramSpec `ebpf:"uprobe_ssl_read_exit"`
	UprobeSslWrite     *ebpf.ProgramSpec `ebpf:"uprobe_ssl_write"`
}

// claude_monitorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type claude_monitorMapSpecs struct {
	Events         *ebpf.MapSpec `ebpf:"events"`
	SslReadArgsMap *ebpf.MapSpec `ebpf:"ssl_read_args_map"`
	TargetPidMap   *ebpf.MapSpec `ebpf:"target_pid_map"`
}

// claude_monitorVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type claude_monitorVariableSpecs struct {
}

// claude_monitorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadClaude_monitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type claude_monitorObjects struct {
	claude_monitorPrograms
	claude_monitorMaps
	claude_monitorVariables
}

func (o *claude_monitorObjects) Close() error {
	return _Claude_monitorClose(
		&o.claude_monitorPrograms,
		&o.claude_monitorMaps,
	)
}

// claude_monitorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadClaude_monitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type claude_monitorMaps struct {
	Events         *ebpf.Map `ebpf:"events"`
	SslReadArgsMap *ebpf.Map `ebpf:"ssl_read_args_map"`
	TargetPidMap   *ebpf.Map `ebpf:"target_pid_map"`
}

func (m *claude_monitorMaps) Close() error {
	return _Claude_monitorClose(
		m.Events,
		m.SslReadArgsMap,
		m.TargetPidMap,
	)
}

// claude_monitorVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadClaude_monitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type claude_monitorVariables struct {
}

// claude_monitorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadClaude_monitorObjects or ebpf.CollectionSpec.LoadAndAssign.
type claude_monitorPrograms struct {
	UprobeSslReadEntry *ebpf.Program `ebpf:"uprobe_ssl_read_entry"`
	UprobeSslReadExit  *ebpf.Program `ebpf:"uprobe_ssl_read_exit"`
	UprobeSslWrite     *ebpf.Program `ebpf:"uprobe_ssl_write"`
}

func (p *claude_monitorPrograms) Close() error {
	return _Claude_monitorClose(
		p.UprobeSslReadEntry,
		p.UprobeSslReadExit,
		p.UprobeSslWrite,
	)
}

func _Claude_monitorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed claude_monitor_x86_bpfel.o
var _Claude_monitorBytes []byte
